/**
 * バリデーション定数。
 * Zodスキーマと frontend の maxLength 等で共通利用する。
 */
export const VALIDATION = {
  ACTIVITY_NAME_MAX: 20,
  ACTIVITY_DESCRIPTION_MAX: 500,
  ACTIVITY_LABEL_MAX: 50,
  ACTIVITY_EMOJI_MAX: 20,
  ACTIVITY_UNIT_MAX: 10,
  KIND_NAME_MAX: 10,
  KIND_COLOR_MAX: 20,
  TASK_TITLE_MAX: 20,
  QUANTITY_MIN: 0,
  QUANTITY_MAX: 999999,
  MEMO_MAX: 1000,
  API_KEY_NAME_MAX: 255,
  CONTACT_EMAIL_MAX: 254,
  CONTACT_BODY_MAX: 1000,
  PASSWORD_MIN: 8,
  PASSWORD_MAX: 100,
  LOGIN_ID_MAX: 100,
  DATE_MAX: 10,
} as const;
