services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoapp
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
