services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - ./db-data:/var/lib/postgresql/data
    command: >
      postgres -c log_statement=all
    ports:
      - 5435:5432
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
