import {
  API_KEY_SCOPES,
  API_KEY_SCOPE_DESCRIPTIONS,
} from "../../packages/domain/apiKey/apiKeySchema";
import type { Param } from "./zodWalker";

export type Endpoint = {
  method: string;
  path: string;
  description: string;
  scope: string;
  queryParams?: Param[];
  requestBody?: Param[];
};

export type EndpointGroup = {
  id: string;
  title: string;
  description: string;
  endpoints: Endpoint[];
};

function formatParam(p: Param): string {
  const parts = [
    `          name: ${JSON.stringify(p.name)},`,
    `          type: ${JSON.stringify(p.type)},`,
    `          required: ${p.required},`,
    `          description: ${JSON.stringify(p.description)},`,
  ];
  return `        {\n${parts.join("\n")}\n        }`;
}

function formatEndpoint(e: Endpoint): string {
  const lines: string[] = [
    `      method: ${JSON.stringify(e.method)},`,
    `      path: ${JSON.stringify(e.path)},`,
    `      description: ${JSON.stringify(e.description)},`,
    `      scope: ${JSON.stringify(e.scope)},`,
  ];
  if (e.queryParams && e.queryParams.length > 0) {
    lines.push(
      `      queryParams: [\n${e.queryParams.map(formatParam).join(",\n")},\n      ],`,
    );
  }
  if (e.requestBody && e.requestBody.length > 0) {
    lines.push(
      `      requestBody: [\n${e.requestBody.map(formatParam).join(",\n")},\n      ],`,
    );
  }
  return `    {\n${lines.join("\n")}\n    }`;
}

function formatGroup(g: EndpointGroup): string {
  const endpoints = g.endpoints.map(formatEndpoint).join(",\n");
  return [
    "  {",
    `    id: ${JSON.stringify(g.id)},`,
    `    title: ${JSON.stringify(g.title)},`,
    `    description: ${JSON.stringify(g.description)},`,
    `    endpoints: [\n${endpoints},\n    ],`,
    "  }",
  ].join("\n");
}

export function render(groups: EndpointGroup[]): string {
  const scopeEntries = API_KEY_SCOPES.map(
    (s) =>
      `  { scope: ${JSON.stringify(s)}, description: ${JSON.stringify(
        API_KEY_SCOPE_DESCRIPTIONS[s],
      )} },`,
  ).join("\n");

  const groupsBody = groups.map(formatGroup).join(",\n");

  return `// DO NOT EDIT. Generated by scripts/generate-api-reference.
// Run \`pnpm generate:api-reference\` to regenerate.

export type HttpMethod = "GET" | "POST" | "PUT" | "DELETE";

export type Param = {
  name: string;
  type: string;
  required: boolean;
  description: string;
};

export type Endpoint = {
  method: HttpMethod;
  path: string;
  description: string;
  scope: string;
  queryParams?: Param[];
  requestBody?: Param[];
};

export type EndpointGroup = {
  id: string;
  title: string;
  description: string;
  endpoints: Endpoint[];
};

export const API_SCOPES = [
${scopeEntries}
] as const;

export const ENDPOINT_GROUPS: EndpointGroup[] = [
${groupsBody},
];
`;
}
