/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ActikoRouteImport } from './routes/actiko'
import { Route as IndexRouteImport } from './routes/index'

const ActikoRoute = ActikoRouteImport.update({
  id: '/actiko',
  path: '/actiko',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actiko': typeof ActikoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actiko': typeof ActikoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actiko': typeof ActikoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/actiko'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/actiko'
  id: '__root__' | '/' | '/actiko'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActikoRoute: typeof ActikoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/actiko': {
      id: '/actiko'
      path: '/actiko'
      fullPath: '/actiko'
      preLoaderRoute: typeof ActikoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActikoRoute: ActikoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
