/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingImport } from './routes/setting'
import { Route as DailyImport } from './routes/daily'
import { Route as IndexImport } from './routes/index'
import { Route as ActivityStatsImport } from './routes/activity/stats'

// Create/Update Routes

const SettingRoute = SettingImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRoute,
} as any)

const DailyRoute = DailyImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ActivityStatsRoute = ActivityStatsImport.update({
  id: '/activity/stats',
  path: '/activity/stats',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyImport
      parentRoute: typeof rootRoute
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingImport
      parentRoute: typeof rootRoute
    }
    '/activity/stats': {
      id: '/activity/stats'
      path: '/activity/stats'
      fullPath: '/activity/stats'
      preLoaderRoute: typeof ActivityStatsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/setting': typeof SettingRoute
  '/activity/stats': typeof ActivityStatsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/setting': typeof SettingRoute
  '/activity/stats': typeof ActivityStatsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/setting': typeof SettingRoute
  '/activity/stats': typeof ActivityStatsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/daily' | '/setting' | '/activity/stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/daily' | '/setting' | '/activity/stats'
  id: '__root__' | '/' | '/daily' | '/setting' | '/activity/stats'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyRoute: typeof DailyRoute
  SettingRoute: typeof SettingRoute
  ActivityStatsRoute: typeof ActivityStatsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyRoute: DailyRoute,
  SettingRoute: SettingRoute,
  ActivityStatsRoute: ActivityStatsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/daily",
        "/setting",
        "/activity/stats"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/daily": {
      "filePath": "daily.tsx"
    },
    "/setting": {
      "filePath": "setting.tsx"
    },
    "/activity/stats": {
      "filePath": "activity/stats.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
