name: Create PR
on:
  push:
    branches:
      - master
jobs:
  gitPrRelease:
    name: git-pr-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
        fetch-depth: 0
    - name: git-pr-release
      uses: bakunyo/git-pr-release-action@v1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PR_RELEASE_BRANCH_PRODUCTION: release
        GIT_PR_RELEASE_BRANCH_STAGING: master
        GIT_PR_RELEASE_LABELS: release